<div style="text-align: justify;line-height: 23px;">
<div><strong><h3 style="font-weight: bold;">TÉRMINOS Y CONDICIONES DEL SITIO</h3> </strong></div>
<hr class="no_margin_top">
<p>
El presente documento describe los términos y condiciones (los “Términos y Condiciones”) que rigen la utilización del sitio en Internet www.telotengo.com (el “Sitio”), incluyendo la contratación de los servicios administrados u ofrecidos en el mismo (los “Servicios”) por o a través de SigmaSystems, C.A. (TELOTENGO.COM).
El usuario del sitio y el usuario registrado (el “Usuario”) de los Servicios declaran tener capacidad jurídica para contratar o representar a quien la tenga, así como haber leído, estar de acuerdo y someterse a los presentes Términos y Condiciones. Si se ha inscrito a un usuario como empresa o persona jurídica, se debe tener capacidad para contratar a nombre de tal entidad y de obligar a la misma en los términos de este acuerdo. Si el Usuario no está de acuerdo con los Términos y Condiciones, debe abstenerse de utilizar el Sitio y/o los Servicios. TELOTENGO.COM podrá negar o terminar la prestación de los Servicios a quienes no posean capacidad para contratar y a quienes no hayan convenido en la anterior declaración
CUALQUIER PERSONA QUE NO ACEPTE ESTOS TÉRMINOS Y CONDICIONES GENERALES, LOS CUALES TIENEN UN CARÁCTER OBLIGATORIO Y VINCULANTE, NO PODRÁ UTILIZAR NUESTRA PÁGINA WEB Y/O LOS PRODUCTOS OFRECIDOS </p>
<br>
<p>
<h4 style="font-weight: bolder;">CONDICIONES GENERALES</h4>

TELOTENGO.COM es un sitio web que ofrece servicios de compra y venta, única y exclusivamente por internet, no existe tienda física donde se puedan retirar los productos o hacer reclamos en relación al servicio del mismo. La misión de TELOTENGO.COM es facilitar al usuario el proceso de compra y venta de una forma segura, por lo que TELOTENGO.COM ha tomado todas las previsiones para asegurar a los usuarios del sitio que sus datos personales suministrados permanezcan confidenciales. Los usuarios podrán disfrutar del servicio de compra en el sitio www.telotengo.com las 24 horas del día, los 7 días de la semana.
www.telotengo.com por ser una aplicacion basada en una tienda en línea, cuenta con un Departamento Especializado de Servicio de Atención al Cliente, mediante el cual se canalizará cualquier duda o inconveniente. Se encuentra activo de lunes a viernes, de 8:00 am a 8:00 pm y los sábados de 8:00 am a 5:00 pm, estando inactivo domingos y feriados.
TELOTENGO.COM se reserva el derecho de modificar, eliminar, sustituir o ingresar, contenido en el sitio, herramientas en la página o los productos ofrecidos, antes de que el usuario oferte por el mismo, todo lo anterior sin previo aviso.
Las promociones y ofertas acordadas y anunciadas por TELOTENGO.COM, serán respetadas en los términos y condiciones en que fueron publicadas y por el tiempo en que las mismas se encuentren vigentes.
www.telotengo.com se encuentra hospedado en una de las plataformas líderes en rendimiento, seguridad y confiabilidad para poder garantizar la confidencialidad y seguridad de dicha información. Sin embargo TELOTENGO.COM no se hace responsable por cualquier violación o usurpación que pueda sufrir el sistema de seguridad del sitio, por terceras personas, fallas en el sistema, en el servidor, en Internet, o cualquier virus que pudiese alojarse en el sistema. Asimismo, TELOTENGO.COM tampoco se hace responsable por la obtención por medios ilegales o violaciones del sistema de la información alojada en nuestro servidor, así como del uso que se haga de la misma.
www.telotengo.com intentará garantizar el uso ininterrumpido y continuado del servicio, sin embargo las consecuencias que se generen con ocasión de fallas en el sistema del mismo o dificultades técnicas u otra razón ajena a la voluntad de TELOTENGO.COM, no serán imputables a TELOTENGO.COM.
Los Términos y Condiciones aquí expresados, podrán ser modificados por TELOTENGO.COM en cualquier momento, y empezaran a entrar en vigencia desde el momento de su publicación en la página de TELOTENGO.COM con lo cual se entenderán aceptados por el Usuario.</p>
<br>
<p>
<h4 style="font-weight: bolder;">REGISTRO DE LOS USUARIOS</h4>

Para poder hacer una compra en TELOTENGO.COM es necesario que el Usuario se registre en el portal web por medio de la solicitud del portal de acceso o por invitacion de los usuarios ya registrados, luego de la aprobacion el usuario debe suministrar toda la información obligatoria que los campos para este fin soliciten, asimismo el Usuario es el responsable de la información suministrada y que la misma sea precisa y veraz. Para TELOTENGO.COM la información suministrada por el Usuario será la información utilizada para verificar el pago y transaciones del producto. Si existe una discrepancia entre la información que se encuentra en el sistema y el Usuario, el responsable será éste último, por lo que el Usuario se compromete a actualizar la información suministrada cuando sea necesario.
La cuenta creada por cada Usuario en TELOTENGO.COM es personal e intransferible, por lo que TELOTENGO.COM no se hace responsable por el uso de la misma por terceras personas autorizadas por él. Asimismo, solo se permite la creación de una sola cuenta en TELOTENGO.COM por Usuario, si se detecta más de una cuenta de Usuario con datos que coincidan, TELOTENGO.COM se reserva el derecho de suspenderlas o inhabilitarlas de manera temporal o indefinida.
Los Usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de los datos personales ingresados. TELOTENGO.COM se reserva el derecho de suspender temporal o definitivamente a aquellos usuarios cuyos datos no hayan podido ser confirmados o resultasen ser fraudulentos o de cualquier forma falsos. En estos casos de inhabilitación, se suspenderán todas las transacciones realizadas, sin que ello genere algún derecho a resarcimiento.
El usuario accederá a su cuenta personal ("Mi Cuenta") mediante el ingreso de su correo electrónico y clave de seguridad personal elegida ("Clave de Seguridad"). El usuario se obliga a mantener la confidencialidad de su clave de seguridad. En caso de que un tercero logre acceder a la cuenta de un usuario sin su consentimiento, y logre ejecutar acciones dentro del sitio o violar la confidencialidad de los datos del usuario, se considera responsabilidad del usuario en la elección de su clave de seguridad.
El usuario será responsable por todas las operaciones efectuadas en su cuenta, pues el acceso a la misma está restringido al ingreso y uso de su clave de seguridad, de conocimiento exclusivo del usuario. El usuario se compromete a notificar a TELOTENGO.COM en forma inmediata y por medio escrito y fehaciente, cualquier uso no autorizado de su cuenta, así como el ingreso por terceros no autorizados a la misma. TELOTENGO.COM se reserva el derecho de rechazar cualquier solicitud de inscripción o de cancelar una inscripción previamente aceptada sin que ello genere algún derecho a indemnización o resarcimiento.
PRIVACIDAD DE LA INFORMACIÓN Y CONFIDENCIALIDAD
Como fue expresado anteriormente, para que un Usuario goce de los servicios de www.telotengo.com, el mismo debe crear una cuenta, ingresando datos de información personal. La información suministrada por los Usuario al momento de crear su cuenta, será almacenada en servidores que mantienen altos niveles de seguridad, tanto física como tecnológica. La información suministrada por el Usuario a TELOTENGO.COM, podrá ser compartida por TELOTENGO.COM para garantizar la prestación del servicio, así como usada por nuestro Departamento de Atención al Cliente para contactar al Usuario y realizarle encuestas, para garantizar las mejoras en la prestación del servicio.
Bajo ningún concepto TELOTENGO.COM podrá vender, alquilar ni traspasar a otras empresas la información personal que cada Usuario ha proporcionado para crear su cuenta en la página, salvo en los supuestos establecidos en los Términos y Condiciones aquí expuestos.
No será responsabilidad deTELOTENGO.COM el uso indebido y no autorizado de un Usuario o un tercero, de la información suministrada en la página.www.telotengo.com reitera que hará todos los esfuerzos físicos y tecnológicos para mantener la información suministrada de manera segura y confidencial.
Asimismo, TELOTENGO.COM tampoco será responsable de la información que los Usuarios divulguen a terceros por redes sociales, foros o cualquier otro medio.</p>
<br>
<p>
<h4 style="font-weight: bolder;">COMUNICACIONES DE PROMOCIONES</h4>

Los Usuarios pueden autorizar en su cuenta a TELOTENGO.COM, para enviarles promociones al correo electrónico registrado en su Perfil.
El Cliente podrá solicitar la suspensión de toda comunicación promocional o publicitaria enviada a su correo electrónico en su Perfil, desactivando la opción destinada para tal fin.</p>
<br>
<p>
<h4 style="font-weight: bolder;">CONDICIONES DE LA COMPRA</h4>

Para que el Usuario pueda realizar y confirmar una compra en TELOTENGO.COM es necesario e indispensable que acepte los Términos y Condiciones establecidos en este texto. Los procesos de recepción del pago, son ajenos a TELOTENGO.COM y son gestionados por las entidades bancarias, por lo que TELOTENGO.COM no se hace responsable por las fallas de comunicación que ellas presenten, ni por las consecuencias que se desprendan de las actuaciones de las mismas. Asimismo, TELOTENGO.COM no se hace responsable por los daños o perjuicios que se originen con la manipulación hecha por terceros, que accedan a la red de manera no autorizada, pese a las herramientas de prevención implementadas en la página web.
La compra será aceptada al momento que el Usuario haya hecho el pedido y oprimido el botón de “FINALIZAR COMPRA” y será procesada únicamente al momento en que sea confirmado el pago hecho por el Usuario. La validez del pedido es de dos días hábiles, entre la confirmación del pedido y la realización efectiva del pago. Después de transcurrido este tiempo, sin haber sido confirmado el pago, la compra será cancelada automáticamente por el sistema y el Usuario deberá realizar de nuevo el pedido. TELOTENGO.COM no se hace responsable por el cambio de inventario y de precios de los productos que pueda existir entre la cancelación del pedido y la realización de la nueva orden por parte del Usuario.
Tomando en cuenta que www.telotengo.com es una plataforma donde el precio y la cantidad de inventario ofrecido lo fija exclusivamente el Aliado Comercial, éste declara que la determinación de dicho precio se efectúa en estricto cumplimiento a las normas legales y sub-legales vigentes en Venezuela, en especial aquellas relacionadas con regulación de precios, márgenes de ganancia permitidos o cualesquiera otras normativas actuales o futuras relacionadas con dichos precios que fueren aplicables al momento de efectuar la oferta y hasta la conclusión de la transacción de venta a que ésta diere lugar.
Todo impuesto o tasa que graven o recaigan sobre los productos sometidos a venta, así como los que recaigan sobre las operaciones de venta, tales como el Impuesto al Valor Agregado (IVA), serán por única y exclusiva cuenta del cliente o usuario, los cuales serán pagados al momento en que éste realice el pedido en el sitio web, y será reflejado en la factura definitiva que le sea entregada al cliente o usuario en el momento de entrega del producto. Recordamos que el Aliado Comercial está obligado a emitir factura o ticket por sus ventas, salvo que se encuentre expresamente eximido de hacerlo por la normativa fiscal vigente. Asimismo, el envío del producto será incluido en los costos de la compra, como se mencionó anteriormente, TELOTENGO.COM es una aplicaci[on en línea y los envíos se gestionan por mutuo acuerdo entre las partes Seleccionando como medio las empresas de envío (ZOOM, DHL, entre otros).
TELOTENGO.COM se reserva el derecho de cancelar cualquier orden que no apruebe los filtros de seguridad requeridos para la aprobación de las mismas.</p>
<br>
<p>
<h4 style="font-weight: bolder;">GARANTÍA Y DEVOLUCIONES</h4>

Si el producto adquirido en TELOTENGO.COM llegase a presentar defectos o desperfectos técnicos, el Usuario podrá activar el servicio Postventa que ofreceTELOTENGO.COM.
Para conocer los plazos de garantía de cualquier producto, puedes comunicarte con nuestro Departamento de Atención al Cliente.
</p> 
</div>